name = "location-data-api"
main = "src/index.ts"
compatibility_date = "2024-12-18"
node_compat = true

[[ d1_databases ]]
binding = "DB"
database_name = "location-data-db"
database_id = "967504b1-ca58-4f93-8e6f-f94da744a5db"
migrations_dir = "drizzle/migrations"

[vars]
ENVIRONMENT = "development"
BETTER_AUTH_SECRET = "dev-secret-key-change-in-production-12345"
BETTER_AUTH_URL = "http://127.0.0.1:8787"
