name = "location-data-api"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

# Enable logging
[observability]
enabled = true

[[ d1_databases ]]
binding = "DB"
database_name = "location-data-db"
database_id = "967504b1-ca58-4f93-8e6f-f94da744a5db"
migrations_dir = "drizzle/migrations"

[vars]
ENVIRONMENT = "production"
BETTER_AUTH_URL = "https://location-data-app.vercel.app"
